// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/employee-management/internal/di"
	usecase "github.com/mickamy/employee-management/internal/feature/assignment/usecase"
)

// NewAssignment initializes dependencies and constructs Assignment.
func NewAssignment(infra di.Infra) *Assignment {
	assign := usecase.NewAssignEmployee(infra)
	release := usecase.NewReleaseAssignment(infra)
	revoke := usecase.NewRevokeAssignment(infra)
	revokeRelease := usecase.NewRevokeRelease(infra)
	current := usecase.NewGetCurrentAssignment(infra)
	history := usecase.NewListAssignmentHistory(infra)
	manager := usecase.NewListManagerHistory(infra)

	return &Assignment{
		assign:        assign,
		release:       release,
		revoke:        revoke,
		revokeRelease: revokeRelease,
		current:       current,
		history:       history,
		manager:       manager,
	}
}
