// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/employee-management/internal/di"
	usecase "github.com/mickamy/employee-management/internal/feature/organization/usecase"
)

// NewOrganization initializes dependencies and constructs Organization.
func NewOrganization(infra di.Infra) *Organization {
	create := usecase.NewCreateDepartment(infra)
	rename := usecase.NewRenameDepartment(infra)
	list := usecase.NewListDepartments(infra)

	return &Organization{
		create: create,
		rename: rename,
		list:   list,
	}
}
