// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/employee-management/internal/di"
	repository "github.com/mickamy/employee-management/internal/feature/assignment/repository"
	repository2 "github.com/mickamy/employee-management/internal/feature/employee/repository"
	repository3 "github.com/mickamy/employee-management/internal/feature/organization/repository"
)

// NewAssignEmployee initializes dependencies and constructs AssignEmployee.
func NewAssignEmployee(infra di.Infra) *AssignEmployee {
	tx := infra.Transactor
	reader := infra.Reader
	assignmentStreamRepository := repository.NewStream(reader)
	assignmentViewRepository := repository.NewAssignmentView(reader)
	employeeRepository := repository2.NewEmployee(reader)
	departmentRepository := repository3.NewDepartment(reader)

	return &AssignEmployee{
		tx:                         tx,
		assignmentStreamRepository: assignmentStreamRepository,
		assignmentViewRepository:   assignmentViewRepository,
		employeeRepository:         employeeRepository,
		departmentRepository:       departmentRepository,
	}
}

// NewGetCurrentAssignment initializes dependencies and constructs GetCurrentAssignment.
func NewGetCurrentAssignment(infra di.Infra) *GetCurrentAssignment {
	tx := infra.ReadTransactor
	reader := infra.Reader
	assignmentRepository := repository.NewAssignment(reader)

	return &GetCurrentAssignment{
		tx:                   tx,
		assignmentRepository: assignmentRepository,
	}
}

// NewListAssignmentHistory initializes dependencies and constructs ListAssignmentHistory.
func NewListAssignmentHistory(infra di.Infra) *ListAssignmentHistory {
	tx := infra.ReadTransactor
	reader := infra.Reader
	assignmentRepository := repository.NewAssignment(reader)

	return &ListAssignmentHistory{
		tx:                   tx,
		assignmentRepository: assignmentRepository,
	}
}

// NewListManagerHistory initializes dependencies and constructs ListManagerHistory.
func NewListManagerHistory(infra di.Infra) *ListManagerHistory {
	tx := infra.ReadTransactor
	reader := infra.Reader
	assignmentRepository := repository.NewAssignment(reader)
	employeeRepository := repository2.NewEmployee(reader)

	return &ListManagerHistory{
		tx:                   tx,
		assignmentRepository: assignmentRepository,
		employeeRepository:   employeeRepository,
	}
}

// NewReleaseAssignment initializes dependencies and constructs ReleaseAssignment.
func NewReleaseAssignment(infra di.Infra) *ReleaseAssignment {
	tx := infra.Transactor
	reader := infra.Reader
	assignmentStreamRepository := repository.NewStream(reader)
	assignmentViewRepository := repository.NewAssignmentView(reader)

	return &ReleaseAssignment{
		tx:                         tx,
		assignmentStreamRepository: assignmentStreamRepository,
		assignmentViewRepository:   assignmentViewRepository,
	}
}

// NewRevokeAssignment initializes dependencies and constructs RevokeAssignment.
func NewRevokeAssignment(infra di.Infra) *RevokeAssignment {
	tx := infra.Transactor
	reader := infra.Reader
	assignmentStreamRepository := repository.NewStream(reader)
	assignmentViewRepository := repository.NewAssignmentView(reader)

	return &RevokeAssignment{
		tx:                         tx,
		assignmentStreamRepository: assignmentStreamRepository,
		assignmentViewRepository:   assignmentViewRepository,
	}
}

// NewRevokeRelease initializes dependencies and constructs RevokeRelease.
func NewRevokeRelease(infra di.Infra) *RevokeRelease {
	tx := infra.Transactor
	reader := infra.Reader
	assignmentStreamRepository := repository.NewStream(reader)
	assignmentViewRepository := repository.NewAssignmentView(reader)

	return &RevokeRelease{
		tx:                         tx,
		assignmentStreamRepository: assignmentStreamRepository,
		assignmentViewRepository:   assignmentViewRepository,
	}
}
