// Code generated by mapgen. DO NOT EDIT.

package converter

import (
	employeev1 "github.com/mickamy/employee-management/gen/employee/v1"
	"github.com/mickamy/employee-management/internal/feature/employee/model"
	"github.com/mickamy/employee-management/internal/lib/converters"
)

// EmployeeToEmployeev1 maps model.Employee to *employeev1.Employee.
func EmployeeToEmployeev1(src model.Employee) *employeev1.Employee {
	return &employeev1.Employee{
		Id:      converters.UUIDToString(src.ID),
		Code:    src.Code,
		Name:    src.Name,
		Email:   src.Email,
		HiredOn: converters.ToDate(src.HiredOn),
	}
}
