// Code generated by automapper. DO NOT EDIT.

package converter

import (
	employeev1 "github.com/mickamy/employee-management/gen/employee/v1"
	"github.com/mickamy/employee-management/internal/feature/employee/model"
	"github.com/mickamy/employee-management/internal/lib/converters"
)

// ToV1EmployeePtr converts *Employee to *Employee.
func ToV1EmployeePtr(src *model.Employee) *employeev1.Employee {
	if src == nil {
		return nil
	}

	return &employeev1.Employee{
		Id:      converters.UUIDToString(src.ID),
		Code:    src.Code,
		Name:    src.Name,
		Email:   src.Email,
		HiredOn: converters.ToDate(src.HiredOn),
	}

}

// ToV1Employee converts Employee to Employee.
func ToV1Employee(src model.Employee) employeev1.Employee {

	return employeev1.Employee{
		Id:      converters.UUIDToString(src.ID),
		Code:    src.Code,
		Name:    src.Name,
		Email:   src.Email,
		HiredOn: converters.ToDate(src.HiredOn),
	}

}
