// Code generated by automapper. DO NOT EDIT.

package converter

import (
	"fmt"

	"github.com/google/uuid"
	employeev1 "github.com/mickamy/employee-management/gen/employee/v1"
	"github.com/mickamy/employee-management/internal/feature/employee/model"
	"github.com/mickamy/employee-management/internal/lib/converters"
)

// FromV1EmployeePtr converts *Employee to *Employee.
func FromV1EmployeePtr(src *employeev1.Employee) (*model.Employee, error) {
	if src == nil {
		return nil, nil
	}

	conv0, err := uuid.Parse(src.Id)
	if err != nil {
		return nil, fmt.Errorf("ID: %w", err)
	}

	return &model.Employee{
		ID:      conv0,
		Code:    src.Code,
		Name:    src.Name,
		Email:   src.Email,
		HiredOn: converters.ToTime(src.HiredOn),
	}, nil

}

// FromV1Employee converts Employee to Employee.
func FromV1Employee(src employeev1.Employee) (model.Employee, error) {

	conv0, err := uuid.Parse(src.Id)
	if err != nil {
		return model.Employee{}, fmt.Errorf("ID: %w", err)
	}

	return model.Employee{
		ID:      conv0,
		Code:    src.Code,
		Name:    src.Name,
		Email:   src.Email,
		HiredOn: converters.ToTime(src.HiredOn),
	}, nil

}
