// Code generated by standin. DO NOT EDIT.

package fixture

import (
	"github.com/brianvoe/gofakeit/v7"

	"github.com/mickamy/employee-management/internal/feature/employee/model"
)

func Employee(setters ...func(m *model.Employee)) model.Employee {
	m := model.Employee{
		Code:    gofakeit.Word(),
		Name:    gofakeit.Name(),
		Email:   gofakeit.Email(),
		HiredOn: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func EmployeeHire(setters ...func(m *model.EmployeeHire)) model.EmployeeHire {
	m := model.EmployeeHire{
		HiredOn: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}
