// Code generated by injector. DO NOT EDIT.

package server

import (
	di "github.com/mickamy/employee-management/internal/di"
	handler "github.com/mickamy/employee-management/internal/feature/employee/handler"
	handler2 "github.com/mickamy/employee-management/internal/feature/organization/handler"
)

// NewHandlers initializes dependencies and constructs Handlers.
func NewHandlers(infra di.Infra) *Handlers {
	employee := handler.NewEmployee(infra)
	organization := handler2.NewOrganization(infra)

	return &Handlers{
		Employee:     employee,
		Organization: organization,
	}
}
