// Code generated by injector. DO NOT EDIT.

package di

import (
	context "context"
	config "github.com/mickamy/employee-management/internal/config"
)

// NewConfig initializes dependencies and constructs Config.
func NewConfig() *Config {
	app := config.ParseApp()
	database := config.ParseDatabase()

	return &Config{
		App:      app,
		Database: database,
	}
}

// NewInfra initializes dependencies and constructs Infra.
func NewInfra(context2 context.Context, config2 *Config) (*Infra, error) {
	database := config2.Database
	writer, err := provideWriter(context2, database)
	if err != nil {
		return nil, err
	}
	reader, err := provideReader(context2, database)
	if err != nil {
		return nil, err
	}
	transactor := provideTransactor(writer)
	readTransactor := provideReadTransactor(reader)

	return &Infra{
		Writer:         writer,
		Reader:         reader,
		Transactor:     transactor,
		ReadTransactor: readTransactor,
	}, nil
}
