// Code generated by injector. DO NOT EDIT.

package di

import (
	context "context"
	config "github.com/mickamy/employee-management/internal/config"
)

// NewConfig initializes dependencies and constructs Config.
func NewConfig() *Config {
	database := config.ParseDatabase()

	return &Config{
		Database: database,
	}
}

// NewInfra initializes dependencies and constructs Infra.
func NewInfra(context2 context.Context, config2 *Config) (*Infra, error) {
	database := config2.Database
	writer, err := provideWriter(context2, database)
	if err != nil {
		return nil, err
	}
	reader, err := provideReader(context2, database)
	if err != nil {
		return nil, err
	}

	return &Infra{
		Writer: writer,
		Reader: reader,
	}, nil
}
