// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/employee-management/internal/di"
	usecase "github.com/mickamy/employee-management/internal/feature/employee/usecase"
)

// NewFeature initializes dependencies and constructs Feature.
func NewFeature(infra di.Infra) *Feature {
	hire := usecase.NewHireEmployee(infra)
	get := usecase.NewGetEmployee(infra)
	list := usecase.NewListEmployees(infra)

	return &Feature{
		hire: hire,
		get:  get,
		list: list,
	}
}
