// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/employee-management/internal/di"
	usecase "github.com/mickamy/employee-management/internal/feature/employee/usecase"
)

// NewHandler initializes dependencies and constructs Handler.
func NewHandler(infra di.Infra) *Handler {
	hire := usecase.NewHireEmployee(infra)
	get := usecase.NewGetEmployee(infra)
	list := usecase.NewListEmployees(infra)

	return &Handler{
		hire: hire,
		get:  get,
		list: list,
	}
}
