// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/employee-management/internal/di"
	usecase "github.com/mickamy/employee-management/internal/feature/employee/usecase"
)

// NewEmployee initializes dependencies and constructs Employee.
func NewEmployee(infra di.Infra) *Employee {
	hire := usecase.NewHireEmployee(infra)
	get := usecase.NewGetEmployee(infra)
	list := usecase.NewListEmployees(infra)

	return &Employee{
		hire: hire,
		get:  get,
		list: list,
	}
}
