// Code generated by standin. DO NOT EDIT.

package fixture

import (
	"github.com/brianvoe/gofakeit/v7"
	"github.com/google/uuid"

	"github.com/mickamy/employee-management/internal/feature/organization/model"
)

func Department(setters ...func(m *model.Department)) model.Department {
	m := model.Department{
		ID:   uuid.MustParse(gofakeit.UUID()),
		Code: gofakeit.Word(),
		Name: gofakeit.Name(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}
