// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignment_queries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearAssignmentViewRelease = `-- name: ClearAssignmentViewRelease :exec
UPDATE assignment_view
SET released_on = NULL
WHERE id = $1
`

func (q *Queries) ClearAssignmentViewRelease(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignmentViewRelease, id)
	return err
}

const deleteAssignmentView = `-- name: DeleteAssignmentView :exec
DELETE
FROM assignment_view
WHERE id = $1
`

func (q *Queries) DeleteAssignmentView(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignmentView, id)
	return err
}

const findAssignmentStream = `-- name: FindAssignmentStream :one
SELECT stream_id
FROM assignment_events
WHERE event_type = 'AssignmentDecided'
  AND payload ->> 'assignment_id' = $1::text
`

func (q *Queries) FindAssignmentStream(ctx context.Context, assignmentID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findAssignmentStream, assignmentID)
	var stream_id uuid.UUID
	err := row.Scan(&stream_id)
	return stream_id, err
}

const getCurrentAssignment = `-- name: GetCurrentAssignment :one
SELECT id, employee_id, department_id, position, assigned_on, released_on
FROM assignment_view
WHERE employee_id = $1
  AND assigned_on <= $2
  AND (released_on IS NULL OR released_on > $2)
ORDER BY assigned_on DESC
LIMIT 1
`

type GetCurrentAssignmentParams struct {
	EmployeeID uuid.UUID
	Today      time.Time
}

func (q *Queries) GetCurrentAssignment(ctx context.Context, arg GetCurrentAssignmentParams) (AssignmentView, error) {
	row := q.db.QueryRow(ctx, getCurrentAssignment, arg.EmployeeID, arg.Today)
	var i AssignmentView
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.Position,
		&i.AssignedOn,
		&i.ReleasedOn,
	)
	return i, err
}

const insertAssignmentView = `-- name: InsertAssignmentView :exec
INSERT INTO assignment_view (id, employee_id, department_id, position, assigned_on)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAssignmentViewParams struct {
	ID           uuid.UUID
	EmployeeID   uuid.UUID
	DepartmentID uuid.UUID
	Position     string
	AssignedOn   time.Time
}

func (q *Queries) InsertAssignmentView(ctx context.Context, arg InsertAssignmentViewParams) error {
	_, err := q.db.Exec(ctx, insertAssignmentView,
		arg.ID,
		arg.EmployeeID,
		arg.DepartmentID,
		arg.Position,
		arg.AssignedOn,
	)
	return err
}

const listAssignmentHistory = `-- name: ListAssignmentHistory :many
SELECT id, employee_id, department_id, position, assigned_on, released_on
FROM assignment_view
WHERE employee_id = $1
ORDER BY assigned_on, id
`

func (q *Queries) ListAssignmentHistory(ctx context.Context, employeeID uuid.UUID) ([]AssignmentView, error) {
	rows, err := q.db.Query(ctx, listAssignmentHistory, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssignmentView
	for rows.Next() {
		var i AssignmentView
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.DepartmentID,
			&i.Position,
			&i.AssignedOn,
			&i.ReleasedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAssignmentView = `-- name: ReleaseAssignmentView :exec
UPDATE assignment_view
SET released_on = $2
WHERE id = $1
`

type ReleaseAssignmentViewParams struct {
	ID         uuid.UUID
	ReleasedOn *time.Time
}

func (q *Queries) ReleaseAssignmentView(ctx context.Context, arg ReleaseAssignmentViewParams) error {
	_, err := q.db.Exec(ctx, releaseAssignmentView, arg.ID, arg.ReleasedOn)
	return err
}
