// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type AssignmentView struct {
	ID           uuid.UUID
	EmployeeID   uuid.UUID
	DepartmentID uuid.UUID
	Position     string
	AssignedOn   time.Time
	ReleasedOn   *time.Time
}
