// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department_queries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :exec
INSERT INTO departments (id, code, name)
VALUES ($1, $2, $3)
`

type CreateDepartmentParams struct {
	ID   uuid.UUID
	Code string
	Name string
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) error {
	_, err := q.db.Exec(ctx, createDepartment, arg.ID, arg.Code, arg.Name)
	return err
}

const departmentExists = `-- name: DepartmentExists :one
SELECT EXISTS (SELECT 1 FROM departments WHERE id = $1)
`

func (q *Queries) DepartmentExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, departmentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, code, name
FROM departments
ORDER BY code
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameDepartment = `-- name: RenameDepartment :one
UPDATE departments
SET name = $2
WHERE id = $1
RETURNING id, code, name
`

type RenameDepartmentParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameDepartment(ctx context.Context, arg RenameDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, renameDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}
