// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID   uuid.UUID
	Code string
	Name string
}

type Employee struct {
	ID    uuid.UUID
	Code  string
	Name  string
	Email string
}

type EmployeeHire struct {
	ID         uuid.UUID
	EmployeeID uuid.UUID
	HiredOn    pgtype.Date
}
