// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/employee-management/internal/di"
	repository "github.com/mickamy/employee-management/internal/feature/organization/repository"
)

// NewCreateDepartment initializes dependencies and constructs CreateDepartment.
func NewCreateDepartment(infra di.Infra) *CreateDepartment {
	tx := infra.Transactor
	reader := infra.Reader
	departmentRepository := repository.NewDepartment(reader)

	return &CreateDepartment{
		tx:                   tx,
		departmentRepository: departmentRepository,
	}
}

// NewListDepartments initializes dependencies and constructs ListDepartments.
func NewListDepartments(infra di.Infra) *ListDepartments {
	tx := infra.ReadTransactor
	reader := infra.Reader
	departmentRepository := repository.NewDepartment(reader)

	return &ListDepartments{
		tx:                   tx,
		departmentRepository: departmentRepository,
	}
}

// NewRenameDepartment initializes dependencies and constructs RenameDepartment.
func NewRenameDepartment(infra di.Infra) *RenameDepartment {
	tx := infra.Transactor
	reader := infra.Reader
	departmentRepository := repository.NewDepartment(reader)

	return &RenameDepartment{
		tx:                   tx,
		departmentRepository: departmentRepository,
	}
}
