// Code generated by mapgen. DO NOT EDIT.

package converter

import (
	organizationv1 "github.com/mickamy/employee-management/gen/organization/v1"
	"github.com/mickamy/employee-management/internal/feature/organization/model"
	"github.com/mickamy/employee-management/internal/lib/converters"
)

// DepartmentToOrganizationv1 maps model.Department to *organizationv1.Department.
func DepartmentToOrganizationv1(src model.Department) *organizationv1.Department {
	return &organizationv1.Department{
		Id:   converters.UUIDToString(src.ID),
		Code: src.Code,
		Name: src.Name,
	}
}
