// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/employee-management/internal/di"
	repository "github.com/mickamy/employee-management/internal/feature/employee/repository"
)

// NewGetEmployee initializes dependencies and constructs GetEmployee.
func NewGetEmployee(infra di.Infra) *GetEmployee {
	tx := infra.ReadTransactor
	reader := infra.Reader
	employeeRepository := repository.NewEmployee(reader)

	return &GetEmployee{
		tx:                 tx,
		employeeRepository: employeeRepository,
	}
}

// NewHireEmployee initializes dependencies and constructs HireEmployee.
func NewHireEmployee(infra di.Infra) *HireEmployee {
	tx := infra.Transactor
	reader := infra.Reader
	employeeRepository := repository.NewEmployee(reader)

	return &HireEmployee{
		tx:                 tx,
		employeeRepository: employeeRepository,
	}
}

// NewListEmployees initializes dependencies and constructs ListEmployees.
func NewListEmployees(infra di.Infra) *ListEmployees {
	tx := infra.ReadTransactor
	reader := infra.Reader
	employeeRepository := repository.NewEmployee(reader)

	return &ListEmployees{
		tx:                 tx,
		employeeRepository: employeeRepository,
	}
}
