// Code generated by injector. DO NOT EDIT.

package usecase

import (
	repository "github.com/mickamy/employee-management/internal/feature/employee/repository"
	tx "github.com/mickamy/employee-management/internal/storage/tx"
)

// NewGetEmployee initializes dependencies and constructs GetEmployee.
func NewGetEmployee(readTransactor tx.ReadTransactor, employee repository.Employee) *GetEmployee {
	return &GetEmployee{
		tx:                 readTransactor,
		employeeRepository: employee,
	}
}

// NewHireEmployee initializes dependencies and constructs HireEmployee.
func NewHireEmployee(transactor tx.Transactor, employee repository.Employee) *HireEmployee {
	return &HireEmployee{
		tx:                 transactor,
		employeeRepository: employee,
	}
}

// NewListEmployees initializes dependencies and constructs ListEmployees.
func NewListEmployees(readTransactor tx.ReadTransactor, employee repository.Employee) *ListEmployees {
	return &ListEmployees{
		tx:                 readTransactor,
		employeeRepository: employee,
	}
}
