// Code generated by mapgen. DO NOT EDIT.

package converter

import (
	assignmentv1 "github.com/mickamy/employee-management/gen/assignment/v1"
	"github.com/mickamy/employee-management/internal/feature/assignment/model"
	"github.com/mickamy/employee-management/internal/lib/converters"
	"google.golang.org/genproto/googleapis/type/date"
)

// AssignmentToAssignmentv1 maps model.Assignment to *assignmentv1.Assignment.
func AssignmentToAssignmentv1(src model.Assignment) *assignmentv1.Assignment {
	var v0 *date.Date
	if v1 := src.ReleasedOn; v1 != nil {
		v0 = converters.ToDate(*v1)
	}
	return &assignmentv1.Assignment{
		Id:           converters.UUIDToString(src.ID),
		EmployeeId:   converters.UUIDToString(src.EmployeeID),
		DepartmentId: converters.UUIDToString(src.DepartmentID),
		Position:     converters.ToAssignmentv1Position(src.Position),
		AssignedOn:   converters.ToDate(src.AssignedOn),
		ReleasedOn:   v0,
	}
}

// ManagerTenureToAssignmentv1 maps model.ManagerTenure to *assignmentv1.ManagerTenure.
func ManagerTenureToAssignmentv1(src model.ManagerTenure) *assignmentv1.ManagerTenure {
	var v0 *date.Date
	if v1 := src.EndedOn; v1 != nil {
		v0 = converters.ToDate(*v1)
	}
	return &assignmentv1.ManagerTenure{
		ManagerEmployeeId: converters.UUIDToString(src.ManagerEmployeeID),
		ManagerName:       src.ManagerName,
		DepartmentId:      converters.UUIDToString(src.DepartmentID),
		StartedOn:         converters.ToDate(src.StartedOn),
		EndedOn:           v0,
	}
}
