syntax = "proto3";

package assignment.v1;

import "assignment/v1/assignment.proto";
import "buf/validate/validate.proto";

service AssignmentQueryService {
  rpc GetCurrentAssignment(GetCurrentAssignmentRequest) returns (GetCurrentAssignmentResponse);
  rpc ListAssignmentHistory(ListAssignmentHistoryRequest) returns (ListAssignmentHistoryResponse);
  rpc ListManagerHistory(ListManagerHistoryRequest) returns (ListManagerHistoryResponse);
}

message GetCurrentAssignmentRequest {
  string employee_id = 1 [(buf.validate.field).string.uuid = true];
}

message GetCurrentAssignmentResponse {
  Assignment assignment = 1;
}

message ListAssignmentHistoryRequest {
  string employee_id = 1 [(buf.validate.field).string.uuid = true];
}

message ListAssignmentHistoryResponse {
  repeated Assignment assignments = 1;
}

message ListManagerHistoryRequest {
  string employee_id = 1 [(buf.validate.field).string.uuid = true];
}

message ListManagerHistoryResponse {
  repeated ManagerTenure tenures = 1;
}
