// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_queries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmployee = `-- name: CreateEmployee :exec
INSERT INTO employees (id, code, name, email)
VALUES ($1, $2, $3, $4)
`

type CreateEmployeeParams struct {
	ID    uuid.UUID
	Code  string
	Name  string
	Email string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error {
	_, err := q.db.Exec(ctx, createEmployee,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Email,
	)
	return err
}

const createEmployeeHire = `-- name: CreateEmployeeHire :exec
INSERT INTO employee_hires (id, employee_id, hired_on)
VALUES ($1, $2, $3)
`

type CreateEmployeeHireParams struct {
	ID         uuid.UUID
	EmployeeID uuid.UUID
	HiredOn    time.Time
}

func (q *Queries) CreateEmployeeHire(ctx context.Context, arg CreateEmployeeHireParams) error {
	_, err := q.db.Exec(ctx, createEmployeeHire, arg.ID, arg.EmployeeID, arg.HiredOn)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT e.id, e.code, e.name, e.email, h.hired_on
FROM employees AS e
         INNER JOIN employee_hires AS h ON h.employee_id = e.id
WHERE e.id = $1
`

type GetEmployeeRow struct {
	ID      uuid.UUID
	Code    string
	Name    string
	Email   string
	HiredOn time.Time
}

func (q *Queries) GetEmployee(ctx context.Context, id uuid.UUID) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.HiredOn,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.code, e.name, e.email, h.hired_on
FROM employees AS e
         INNER JOIN employee_hires AS h ON h.employee_id = e.id
WHERE e.id > $1
ORDER BY e.id
LIMIT $2
`

type ListEmployeesParams struct {
	AfterID  uuid.UUID
	PageSize int32
}

type ListEmployeesRow struct {
	ID      uuid.UUID
	Code    string
	Name    string
	Email   string
	HiredOn time.Time
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Email,
			&i.HiredOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
